//
// THIS FILE IS AUTOMATICALLY GENERATED!!
//
// Generated at Mon 07-Jul-2008 by the VDM++ to JAVA Code Generator
// (v8.1.1b - Fri 06-Jun-2008 09:02:11)
//
// Supported compilers:
// jdk1.4
//

// ***** VDMTOOLS START Name=HeaderComment KEEP=NO
// ***** VDMTOOLS END Name=HeaderComment

// ***** VDMTOOLS START Name=package KEEP=NO
package org.overturetool.jml.ast.imp;

// ***** VDMTOOLS END Name=package

// ***** VDMTOOLS START Name=imports KEEP=YES

import jp.co.csk.vdm.toolbox.VDM.*;
import java.util.*;
import org.overturetool.jml.ast.itf.*;
// ***** VDMTOOLS END Name=imports



public class JmlUnaryOperatorQuotes implements IJmlUnaryOperatorQuotes {

// ***** VDMTOOLS START Name=vdmComp KEEP=NO
  static UTIL.VDMCompare vdmComp = new UTIL.VDMCompare();
// ***** VDMTOOLS END Name=vdmComp


















// ***** VDMTOOLS START Name=qmap KEEP=NO
  private static HashMap qmap = new HashMap();
// ***** VDMTOOLS END Name=qmap


// ***** VDMTOOLS START Name=static KEEP=NO
  static {
    try {

      JmlUnaryOperatorQuotes.qmap = new HashMap();
      JmlUnaryOperatorQuotes.qmap.put(IQCARD, new String("<CARD>"));
      JmlUnaryOperatorQuotes.qmap.put(IQMINUS, new String("<MINUS>"));
      JmlUnaryOperatorQuotes.qmap.put(IQTL, new String("<TL>"));
      JmlUnaryOperatorQuotes.qmap.put(IQFLOOR, new String("<FLOOR>"));
      JmlUnaryOperatorQuotes.qmap.put(IQABS, new String("<ABS>"));
      JmlUnaryOperatorQuotes.qmap.put(IQINVERSE, new String("<INVERSE>"));
      JmlUnaryOperatorQuotes.qmap.put(IQPOWER, new String("<POWER>"));
      JmlUnaryOperatorQuotes.qmap.put(IQELEMS, new String("<ELEMS>"));
      JmlUnaryOperatorQuotes.qmap.put(IQDOM, new String("<DOM>"));
      JmlUnaryOperatorQuotes.qmap.put(IQOLD, new String("<OLD>"));
      JmlUnaryOperatorQuotes.qmap.put(IQHD, new String("<HD>"));
      JmlUnaryOperatorQuotes.qmap.put(IQINCREMENT, new String("<INCREMENT>"));
      JmlUnaryOperatorQuotes.qmap.put(IQPLUS, new String("<PLUS>"));
      JmlUnaryOperatorQuotes.qmap.put(IQRNG, new String("<RNG>"));
      JmlUnaryOperatorQuotes.qmap.put(IQLEN, new String("<LEN>"));
      JmlUnaryOperatorQuotes.qmap.put(IQNOT, new String("<NOT>"));
      JmlUnaryOperatorQuotes.qmap.put(IQDECREMENT, new String("<DECREMENT>"));
    }
    catch (Throwable e){

      e.printStackTrace(System.out);
      System.out.println(e.getMessage());
    }
  }
// ***** VDMTOOLS END Name=static


// ***** VDMTOOLS START Name=JmlUnaryOperatorQuotes KEEP=NO
  public JmlUnaryOperatorQuotes () throws CGException {}
// ***** VDMTOOLS END Name=JmlUnaryOperatorQuotes


// ***** VDMTOOLS START Name=getQuoteName KEEP=NO
  static public String getQuoteName (final Long pid) throws CGException {
    return UTIL.ConvertToString(qmap.get(pid));
  }
// ***** VDMTOOLS END Name=getQuoteName


// ***** VDMTOOLS START Name=validQuote KEEP=NO
  static public Boolean validQuote (final Long pid) throws CGException {

    Boolean rexpr_2 = null;
    rexpr_2 = new Boolean(qmap.containsKey(pid));
    return rexpr_2;
  }
// ***** VDMTOOLS END Name=validQuote

}
;
